"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'
import { configureBoneyard } from 'boneyard-js/react'

import _dashboard_portfolio from './dashboard-portfolio.bones.json'
import _dashboard_jobs from './dashboard-jobs.bones.json'
import _coi_detail from './coi-detail.bones.json'
import _dashboard_compare from './dashboard-compare.bones.json'
import _tenants_list from './tenants-list.bones.json'
import _tenant_detail from './tenant-detail.bones.json'
import _checklist from './checklist.bones.json'
import _templates from './templates.bones.json'
import _metrics from './metrics.bones.json'
import _queue_metrics_panel from './queue-metrics-panel.bones.json'
import _cron_scan_panel from './cron-scan-panel.bones.json'

configureBoneyard({"color":"#1a1a1a","darkColor":"#2a2a2a","animate":"shimmer","shimmerColor":"#252525","darkShimmerColor":"#333333","speed":"2s","shimmerAngle":110})

registerBones({
  "dashboard-portfolio": _dashboard_portfolio,
  "dashboard-jobs": _dashboard_jobs,
  "coi-detail": _coi_detail,
  "dashboard-compare": _dashboard_compare,
  "tenants-list": _tenants_list,
  "tenant-detail": _tenant_detail,
  "checklist": _checklist,
  "templates": _templates,
  "metrics": _metrics,
  "queue-metrics-panel": _queue_metrics_panel,
  "cron-scan-panel": _cron_scan_panel,
})
